sensitiveCodepaths:
  # Files only allowed authors can modify
   - 'README.md'
  # - 'controllers/**/*.js'
allowedAuthors:
  usernames:
    # GitHub username
     - 'cktricky'
notificationList:
  # GitHub username or team name
  # - '@DryRunSec/security'
   - '@cktricky'
